version: '3.7'
services:
  nginx:
    build: ./docker
    working_dir: '/var/www/html'
    ports:
      - 80:80
    networks:
      - test-network
    volumes:
      - .:/var/www/html
      - ./docker/nginx-log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - test-network
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password 

networks:
  test-network:
    driver: bridge
