version: '3.7'
services:
  nginx:
    build: ./docker
    container_name: laravel_server
    working_dir: '/var/www/html'
    ports:
      - 80:80
    networks:
      - test-network
    volumes:
      - .:/var/www/html
      - ./docker/nginx-log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - test-network
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    build: ./docker/myredis
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./docker/myredis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/myredis/data:/data
    ports:
      - "6379:6379"
    networks:
      - test-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/logs/:/var/log/rabbitmq/
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
